### ISSUE TITLE
Error running Selenium

### ISSUE THREAD

**Issue by factorlabs** [minkphp/MinkBundle#40]
Hi,

I'm trying to run Mink and Selenium with Symfony. 

My composer.json:

```
"behat/symfony2-extension": "*",
        "behat/mink-extension" : "*",
        "behat/mink-browserkit-driver" : "*",
        "behat/mink-selenium-driver":  "*",
```

My behat.yml:

```
default:
    extensions:
        Behat\Symfony2Extension\Extension:
            mink_driver: true
        Behat\MinkExtension\Extension:
            default_session: 'symfony2'
            javascript_session: selenium
            selenium: ~
        VIPSoft\DoctrineDataFixturesExtension\Extension:
            fixtures: ~
```

I'm running selenium using:
`java -jar selenium-server-standalone-2.28.0.jar`

And the error I'm getting is:
`Unexpected response from Selenium server : ERROR Server Exception: sessionId should not be null; has this session been started yet?`

While I'm trying to run tests.
Thank you for any suggestions!
